### ISSUE TITLE
add time interval function to jsurvival

### ISSUE THREAD

**Issue by sbalci** [sbalci/ClinicoPathJamoviModule#34]
`.b.R`

```r
            if (! is.null(self$options$resids)) {
                calculatedtime <- as.vector(calculatedtime)
                calculatedtime <- jmvcore::toNumeric(calculatedtime)
            }

            if ( ! is.null(self$options$resids)) {
                self$results$resids$setValues(calculatedtime)
            }

```

`.a.yaml`

```yaml
    - name: resids
      title: Residuals
      type: Output

    - name: resids2
      title: Residuals2
      type: Output
```

.u.yaml

```yaml
  - type: VariableSupplier
    persistentItems: false
    stretchFactor: 1
    children:
      - type: TargetLayoutBox
        label: Residuals
        children:
          - type: VariablesListBox
            name: resids
            maxItemCount: 1
            isTarget: true
      - type: TargetLayoutBox
        label: Residuals2
        children:
          - type: VariablesListBox
            name: resids2
            maxItemCount: 1
            isTarget: true
```
